configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/trim.smk"
#include: "rules/sra.smk"
include: "rules/map.smk"
include: "rules/peak.smk"
include: "rules/bw.smk"
include: "rules/annot.smk"
include: "rules/deeptools.smk"
include: "rules/chipatlas.smk"
include: "rules/qc.smk"

rule all:
    input:
        expand("{out_}", out_ = outputs)