SAMPLES: config/samples.tsv
#GEOSAMPLES: config/geo_samples.tsv
#UNITS: config/units.tsv

OUTPUT:
    RUN:
        QC: False
        PEAKS: True
        BWS: True
        CHIPATLASBED: False
        CHIPATLASBIGWIG: False
        IDR: False
    BW_NORMALIZATIONS:
        - rawcount
        - FPM
    MACS_THRESHOLD:
        - 0.01
    BAMPROCESS_PARAMS: -q 30
    CHIPATLASBED_THRESHOLD: '05'

CUT_ADAPTERS: True
UPDATE_CHIPATLAS: False